# Generated by Django 5.0.6 on 2024-05-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookhub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, unique=True)),
                ('cover', models.ImageField(upload_to='')),
                ('author', models.CharField(max_length=65)),
                ('category', models.CharField(max_length=75)),
                ('publisher', models.CharField(max_length=75)),
                ('year', models.IntegerField()),
                ('language', models.CharField(max_length=20)),
                ('pages', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
