# Generated by Django 5.0.6 on 2024-05-13 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookhub', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(upload_to='static/bookhub'),
        ),
    ]
