# Generated by Django 5.0.6 on 2024-05-14 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookhub', '0004_book_availability_alter_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='availability',
            field=models.CharField(default='Available', max_length=13),
        ),
    ]
