# Generated by Django 5.0.6 on 2024-05-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookhub', '0006_book_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_books', to='bookhub.user'),
        ),
    ]
